// Code generated by mockery v2.12.0. DO NOT EDIT.

package commandsrv

import (
	context "context"
	testing "testing"

	mock "github.com/stretchr/testify/mock"
)

// MockCommandFunc is an autogenerated mock type for the CommandFunc type
type MockCommandFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *MockCommandFunc) Execute(_a0 context.Context) {
	_m.Called(_a0)
}

// NewMockCommandFunc creates a new instance of MockCommandFunc. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockCommandFunc(t testing.TB) *MockCommandFunc {
	mock := &MockCommandFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
